### ISSUE TITLE
Do you guys want this to be a package?

### ISSUE THREAD

**Issue by fjaviersanchez** [igmhub/LyaCoLoRe#17]
@andreufont @jfarr03 While testing the code in the `update_DLA` branch I made the package installable by `python setup.py install` (I didn't include the changes in the version that I pushed since this would be a new feature so it is better to include in a different branch). Is this something you'd like to include or do you prefer the modification of `PYTHONPATH` option?

**Comment by andreufont** [comment]
Yes, I think this would be a good idea. Thanks!
