### ISSUE TITLE
low z cut of random quasars

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#21]
mock data go down to z = 1.796 when mock randoms only to z = 1.8
![distrib_qso_low_z](https://user-images.githubusercontent.com/3166436/47573632-052c9980-d8fb-11e8-94f6-2c720b663747.png)

**Comment by fjaviersanchez** [comment]
I think it should be fixed now. I had a hard cut imposing that z_rnd > 1.8 and I took it off.

<img width="594" alt="screen shot 2018-10-30 at 10 14 40 am" src="https://user-images.githubusercontent.com/13971732/47707704-c6fde580-dc2c-11e8-8cb4-240b4f2595fa.png">

(orange are randoms, blue are QSOs)

**Comment by fjaviersanchez** [comment]
I re-ran all the random catalogs in the 4.0.x folders. I am also opening a PR with the newest version of the code

**Comment by andreufont** [comment]
Great @fjaviersanchez !

**Comment by londumas** [comment]
@fjaviersanchez, thanks for looking at this.
The distribution of randoms (red) follows the one of `master.fits:Z_QSO_RSD` (blue).
However the distribution of `quick-2.0/zcat_desi_drq.fits` (green) is different from these two.
@andreufont, Do you have an idea what is happening?

Of course I don't think it is the most important thing to fix for the moment, but it is nice to have a look at it.
![distrib_mocks_qso_random_lowz](https://user-images.githubusercontent.com/3166436/47727386-f22f0780-dc21-11e8-81df-5fefd93ebcdc.png)
![distrib_mocks_qso_random_highz](https://user-images.githubusercontent.com/3166436/47727385-f1967100-dc21-11e8-93c9-4d8406ddbe70.png)

**Comment by andreufont** [comment]
Hi @londumas - the zcat files are generated from the zbest files, that are printed in quickquasars. The particular run that you are looking at was run with --zmin 1.8, so I believe quickquasars did not include the few quasars that happened to be at z<1.8.

**Comment by andreufont** [comment]
@londumas - is this issue fixed? Should we close it?

**Comment by londumas** [comment]
Fixed. Thank you all.
