### ISSUE TITLE
Probability of DLA vs z has a bump

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#24]
The probability of DLA vs. redshift has a bump at z~2.8.
Do you know what is happening? Is it linked to Lyman-beta?

![probability_vs_z](https://user-images.githubusercontent.com/3166436/47574167-38235d00-d8fc-11e8-9ba4-17f0572fa32d.png)

**Comment by fjaviersanchez** [comment]
Honestly, I have no idea, I was thinking that it may be related to the bump at the QSO N(z) but you are dividing by that... It is curious that it also seems to appear in the data. Maybe @andreufont has some ideas?

**Comment by andreufont** [comment]
I wouldn't worry about this. The distribution of quasars is different in the data (BOSS/eBOSS) than in the mocks (expected DESI), so I wouldn't expect this to match. 

About the bump, it might be caused by a dip in the qso distribution?

Instead of looking at this, I would look at the f(z,N) that Alma is plotting. She was plotting this function as a function of N, but you can also plot it as a function of z, for a given range of N. This is the function we want to compare.

**Comment by fjaviersanchez** [comment]
This is the function you are referring to integrated for the N range between 19.5 and 22 that we used for the sims, right? In any case, I think that the shape of that distribution may change a bit with the latest fix (the dependence in NHI is now pretty strong):

![image](https://user-images.githubusercontent.com/13971732/47783954-778ae880-dd04-11e8-857c-41c5d4bc821d.png)

**Comment by londumas** [comment]
@andreufont,

>I wouldn't worry about this. The distribution of quasars is different in the data (BOSS/eBOSS) than in >the mocks (expected DESI), so I wouldn't expect this to match.

I agree, I don't expect data to match mocks, however it gives an idea of what to expect

>About the bump, it might be caused by a dip in the qso distribution?

The distribution of DLA should follow that of the quasars, so I don't see a reason to have a bump.
Or maybe I am wrong and the redshift distribution of the DLA has no reasons to follow that of the quasars.
Maybe the DLA code is using a different quasar distribution than that quasar catalog?

>Instead of looking at this, I would look at the f(z,N) that Alma is plotting. She was plotting this function >as a function of N, but you can also plot it as a function of z, for a given range of N. This is the function >we want to compare.

I disagree, let's keep it simple.
Histograms and ratio of histograms are so simple, and better to use to fix big effects.

**Comment by andreufont** [comment]
The number of DLAs at a given z, does not depend on the number of quasars at the same z, but instead it depends on a weighted integral of quasars above z. 

Imagine that all your quasars had z=3. You wouldn't have any DLA at z=3, but you'd have DLAs at 2.5 < z < 2.95 or so. 

So if there are bumps in the quasar distribution, then this would translate into a smoother bump in the DLA distribution, and the ratio would also have features... I think it is a bit messy.

**Comment by londumas** [comment]
@andreufont, Yes you are totally right. So this is not an issue at all.
