### ISSUE TITLE
Bias of DLA is too low

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#25]
The bias of DLA is too low compared to data. The two plots are giving:
    - the stack in 1d of delta at the rest frame of a DLA
    - the 3D cross-correlation DLA x LYA

![stack_1d](https://user-images.githubusercontent.com/3166436/47574311-89cbe780-d8fc-11e8-855e-eaf0c9daa4af.png)

![3d_cross_lya_dla](https://user-images.githubusercontent.com/3166436/47574320-8df80500-d8fc-11e8-8de0-3e805209b599.png)

**Comment by andreufont** [comment]
I was talking to James about the way we add the DLAs now, and he explained that we are now looking at the peaks of the delta_Gaussian field that already has the extra small scale power. What should be fine, as long as we are using the right value of sigma_gaussian as a function of redshift (I believe this is the case?). 

However, we might be making our lives too complicated, since we could be using the initial Gaussian field directly to decide where to place the DLAs. The extra power just adds random noise, it should not affect the 3D clustering of the DLAs.

Anyway, just an option for debugging ideas. I think it would also be useful to go through the notebook on setting the density threshold, and try to identify either a bug there, or in the implementation in the python code (threshold_dla_bias.ipynb)

**Comment by andreufont** [comment]
@londumas that wouldn't work, since while we use a threshold in the 3D density for quasars, for DLAs we use the 1D density skewers, that have been interpolated from the 3D density using a smoothing kernel. 

The smoothing kernel changes the distribution of density values (PDF), and in particular it changes the variance sigma^2, so we would have to use different thresholds in the quasars and in the DLAs to get the same bias. 

Moreover, the way the quasars are put in CoLoRe is slightly more convoluted, I believe it is not just a density threshold.

**Comment by londumas** [comment]
@andreufont, Ok, I see. I leave you look at that.

**Comment by londumas** [comment]
@fjaviersanchez, I have though of this, but to do so we have to generate different kind of randoms for DLAs. Looking at how flat the ratio is in cell 62 of the QA https://github.com/igmhub/desi_QA/blob/master/Mocks/QA_DLA.ipynb, it seems that it might not be too complicated.
If you generate the randoms, then I will compute the 3D auto-correlation of DLAs.

**Comment by fjaviersanchez** [comment]
Thanks! I'll generate specific randoms for the DLAs.

**Comment by londumas** [comment]
@fjaviersanchez, Currently the catalog of DLA from the mocks that I have created from the transmission file does not have the DESI footprint. We will have to wait for the next version to get DLA mock data and DLA mock randoms on the DESI footprint.

**Comment by fjaviersanchez** [comment]
@londumas That's fine, we can generate the randoms full-sky and cut them later if needed.

**Comment by londumas** [comment]
@fjaviersanchez, ok, works for me. Tell me when it is done and where it is also.

**Comment by andreufont** [comment]
Hi @fjaviersanchez, @londumas, @jfarr03 

A couple of comments on trying to debug the DLA bias:
 - the footprint doesn't matter. I would just measure the cross-correlations of DLA-Lya (or the auto-correlation of DLAs) in the full sky.
 - You could compute the 1D cross-correlation of DLA x QSOs, that should be very fast, and that would already give you b_QSO b_DLA xi(r)
 - If you need a less noisy statistics, we can add more DLAs without changing their bias. Remember that in the current code, we start by identifying the "cells that could store a DLA", and then we decide whether we add one or not given a column density distribution. But the bias of the "cells" is exactly the same as the bias of the DLAs, so we could just write to file (in an extra HDU, even if only for debugging), the position of all the cells that could have hosted a DLA in each line of sight.

**Comment by londumas** [comment]
Hi @andreufont,
- of course the footprint does not matter, however, we need both mock data and mock randoms to be on the same footprint. We already have the 3d DLA-Lya cross-correlation. See second plot on this ticket.
- Good idea, once I have the catalog of mock random, I will compute the 1d cross-correlation of DLA x xQSO
- We have enough statistic, we just need to change the threshold to get a higher bias for DLA.

**Comment by fjaviersanchez** [comment]
@londumas I produced a DLA random catalog at `'/global/projecta/projectdirs/desi/mocks/lya_forest/london/v4.0.0/DLA_randoms.fits.gz'`. It has 15 million objects so feel free to subsample it if needed to get quicker results.

**Comment by fjaviersanchez** [comment]
I am adding everywhere in the sky since the skewers where the DLAs live are placed in the full sky. If I just restricted the randoms to be on the skewers the 1D correlations should be fine but the 3D power would be partially erased (since the angular correlations would be zero in that case because your random catalog has the same clustering as your data).

**Comment by londumas** [comment]
@andreufont, I agree with you. I would place random DLAs only in front of quasars.
Anyway, I will have a look at that file.
However, this test is a bit superfluous, we only know that the bias of DLA is too low.
I would also generate a new catalog of mock data DLA, with a higher threshold. This test would be very simple. Is it fast for you @fjaviersanchez  to do that?

**Comment by andreufont** [comment]
@londumas - the thing is, there is an analytical way to predict the bias as a function of threshold. So instead of "tuning" the threshold, I would like to understand why the analytical prediction didn't work. Specially since we need a threshold as a function of z.

**Comment by fjaviersanchez** [comment]
@londumas that should be easy to do. Currently we fix the bias to 2 at z=2.25 but it can be fixed to whatever value we think is useful.

**Comment by londumas** [comment]
As @andreufont was suggesting it, the randoms are not correct since they don't reproduce the fact that there can be multiple objects along the same line-of-sight. The following plot gives the 3D auto-correlation of DLAs and quasars.
Anyway, comparing the 3d auto-correlation of DLAs and the 3D auto-correlations of quasars we can see that the bias of DLA is very low.
Simply compares the values at rp<4 and rt<4: `xi = 0.3` vs. `xi = 9`.

Let's have @fjaviersanchez, change the threshold to something very high, to blow up the DLA bias, and I will recompute the 3D cross-correlation between DLA and Lya. This will be very simple.

DLA
![auto_3d_dla](https://user-images.githubusercontent.com/3166436/48219485-dde9b980-e349-11e8-952e-cd83c65eb1ac.png)

QSO
![auto_3d_qso](https://user-images.githubusercontent.com/3166436/48219854-eb537380-e34a-11e8-8f70-cb0265aec929.png)

**Comment by londumas** [comment]
@fjaviersanchez, I am not saying that we should do that now, however if we want to get the catalog of mocked DLA randoms, I think we should: select some (ra,dec,z) at random that represent the host quasar and then for each of these set multiple random DLAs, as you do for mocked data DLA.
The consequence is that we will have multiple random DLAs for each random line of sight.
It would be nice also to have a ID for each random line of sight and another for each random DLA.

**Comment by londumas** [comment]
@fjaviersanchez, Did you have time to look into resolving this issue?
I really think that one of the best way to solve this is to change drastically the threshold on delta_gaussian to put DLA. I know @andreufont it will not follow the theoretical formulae, however it will help to see if it is working. Let's aim to have bais_DLA ~ 10, it will make everything easier. Once we measure the bias it will be trivial to reduce it.

**Comment by londumas** [comment]
@jfarr03, Thanks for the work on v5.0.0, it looks good.

I detect a 3d DLAxLya correlation, however I am afraid that it might really be a 3d QSOxLya correlation.
Indeed most of your DLA are now very close to the quasars, this did not used to be the case.
Do you know what might be causing this?
See the following plots.

I intend to redo the 3d correlation removing all DLA within 2000km/s of the quasar.
We will see if this is the effect.

```
import fitsio
import matplotlib.pyplot as plt
import scipy as sp
import scipy.constants

h = fitsio.FITS('/global/projecta/projectdirs/desi/mocks/lya_forest/london/v5.0.0/master_DLA.fits')
zdla = h['DLACAT']['Z_DLA_RSD'][:]
zqso = h['DLACAT']['Z_QSO_RSD'][:]
c = (sp.constants.speed_of_light/1000.)
dv = c*(zdla-zqso)/(1.+zqso)
bins = sp.arange(-200000.,4000.,2000.)
plt.hist(dv,bins=bins,histtype='step',density=True,linewidth=4)
plt.xlabel(r'$\Delta v(z_{\mathrm{DLA}}-z_{\mathrm{QSO}}) \, [\mathrm{km\,s^{-1}}]$')
plt.ylabel(r'$\mathrm{\#}$')
plt.grid()
plt.show()
```
![distrib_dla_qso](https://user-images.githubusercontent.com/3166436/51341279-35915900-1a4e-11e9-8692-b7e9108380c4.png)

![dla_cross_correlation_with_delta](https://user-images.githubusercontent.com/3166436/51341280-35915900-1a4e-11e9-9d21-bbfe2aaf51e5.png)

**Comment by londumas** [comment]
@jfarr03, it works! So the correlation is indeed coming from DLAxLya. We just have to find a way to remove DLA too close to the quasar. Do you have an idea of how to do that?
Thanks for the work! It is very cool to have a proper value for the DLA bias!

**Comment by londumas** [comment]
@jfarr03, I am sending the computation of the cross-correlation DLA x Lya with more data to confirm the good news and see if the beta and the bias is correct.

**Comment by jfarr03** [comment]
Great, glad this seems to have worked! 

On a practical level, removing DLAs from close to the QSOs would be quite straightforward, but I’m not sure how exactly you would physically motivate a method to do so?

**Comment by londumas** [comment]
@jfarr03, what is the size of the pixel of the large scale mode the quasar lives in? Is it something like 2Mpc/h? We could imagine removing all DLA that are basically taken from the same large scale mode of the quasar itself. Do you see what I mean? What is basically the scale of the smoothing to go from a field in each large scale pixel to a continuous field? The size might be 1 or 2 pixels or something of the sort no?

**Comment by andreufont** [comment]
Thanks for looking at it @londumas, I'm glad to see this fixed.

About removing DLAs near the quasar: since quasars are in high density regions, it is normal to also have more DLAs. It is not clear what the DLAxQSO  should look like on small scales, so it is not clear to me that the one in the mocks is incorrect. If you think about it, probably most quasars leave in galaxies that could cause DLAs on a neighbouring line of sight.

These DLAs very close to the quasar are not seen in the data because most DLA finders do not work well near the Lya emission line 

But yes, I think in quickquasars we should only add DLAs that are a bit far from the quasar, at least at least 1000 km/s or so.

**Comment by londumas** [comment]
@jfarr03, I ran with 100,000 forests and all the DLA catalog and it is perfect. See plot bellow.
My plan to close this ticket is to compute the 3d auto-correlation of DLA to get a direct measurement of bias and growth_rate_of_structure for the DLA. Once this is done we can safely resolve this ticket.
Do that sounds like a good plan?

![xcf_dla](https://user-images.githubusercontent.com/3166436/51400364-75ffde00-1b05-11e9-9842-305b1edd6d7e.png)

**Comment by jfarr03** [comment]
That sounds good to me! I'll generate randoms now and will let you know when they're ready

**Comment by jfarr03** [comment]
Oh wait, I hadn't seen @fjaviersanchez's comment on #35! It seems the randoms are already there and ready to go.

**Comment by londumas** [comment]
@jfarr03 and @andreufont,
Perfect the preliminary results on the auto-correlation of DLA confirms that the bias of DLA is good.
Let's resolve this ticket and open a different one to see the issue of minimum distance between the quasar and the DLA in the same forest.

![co_dla_wedge_0_rescale_1](https://user-images.githubusercontent.com/3166436/51404895-0512f300-1b12-11e9-8062-b7af63c329dc.png)

![bias_dla_vs_z](https://user-images.githubusercontent.com/3166436/51404894-0512f300-1b12-11e9-83d7-b1798ffbf89c.png)

where the "data" points are:
```
### Perez-Rafols2017 (DLA, table 3) https://arxiv.org/abs/1709.00889
data['Perez-Rafols2017'] = {'z':[2.3,2.1,2.4,3.0], 'b':[2.00,2.40,1.39,2.27], 'e':[0.19,0.25,0.24,0.29]}
```
