### ISSUE TITLE
Small difference in NHI distribution

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#32]
This ticket inherits from https://github.com/igmhub/LyaCoLoRe/issues/26, now that the distribution in data and mocks are very similar.

Here are the distribution of NHI in mocks and data. You can see that they agree very well.
However, we could work a bit on the high NHI tail of the distribution, at NHI=22.5 we have a one dex difference.

@andreufont, @alxogm, @ngbusca, do we want something even more closer to the data, or this is good enough? Keep in mind that in the data there is the effect of efficiency of detection, bringing some uncertainties in the blue points.

![distribution_nhi](https://user-images.githubusercontent.com/3166436/48573257-e5b8d900-e8c8-11e8-91d5-d02c055db1e2.png)

![distribution_nhi_log10](https://user-images.githubusercontent.com/3166436/48573258-e5b8d900-e8c8-11e8-8fab-c699776a28d7.png)

![fraction_nh1](https://user-images.githubusercontent.com/3166436/48573259-e5b8d900-e8c8-11e8-8a9e-a6efb6ad993e.png)

**Comment by londumas** [comment]
@fjaviersanchez , we will actually need to add low NHI DLA to the mocks, it has been studied in DR12 paper to have an impact of the auto-correlation of Lya. I don't know currently down to which value, but as soon as I know I tell you. Would it be hard to updated that?

**Comment by londumas** [comment]
Page 5 of Bautista et al, https://arxiv.org/pdf/1702.00176.pdf,
```
pixels where the optical depth was above a chosen threshold.
The neutral-hydrogen column densities were drawn randomly
with NHI>10^17.2cm−2, assuming an intrinsic power-law
distribution corrected for self-shielding and normalized to
match the observations of Prochaska et al. (2005). 
```
@fjaviersanchez, can you set the minimum to be 17.2? At the same time we need to keep the following ratio of NHI>20 the same.

![ratio_DLA_qso](https://user-images.githubusercontent.com/3166436/55492810-176eda00-55f5-11e9-960d-ee9bbd7391fc.png)

**Comment by fjaviersanchez** [comment]
@londumas I just updated the code in LyaCoLoRe. @TEtourneau, please feel free to change the `Nmin=20.0` values to `Nmin=17.2`.

**Comment by londumas** [comment]
@fjaviersanchez, thanks. @jfarr03, could you send a production of the DLA catalog.
No need yet for updating the transmission files.

**Comment by jfarr03** [comment]
@londumas Do you mean for v6.0.0? The DLAs are generated alongside the skewers at the moment and generating a new catalog just collects the DLAs from each of the transmission files. To generate new DLAs with the different Nmin value would mean generating a new set of skewers (v6.1.0). Is this what you would like?

**Comment by londumas** [comment]
I mean fix that so in the next production it will be ok.

**Comment by londumas** [comment]
Fiked in latests versions
