### ISSUE TITLE
Fix some name in fits file 

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#34]
@jfarr03, please feel free to disagree.

Some names in fits file are not perfect (according to me):
- for "master_DLA.fits": I would rather have no space in the `EXTNAME = DLA CATALOG`.
`DLACAT` is perfect to be also less than 8 characters, but `DLACATALOG` would be ok also.

- I don't think you need to repeat the following in all header of all hdu of a given transmission file. Just for the `hdu=1` would be ok:
```
HPXNSIDE=                   16
HPXPIXEL=                    0
HPXNEST =                    T
LYA     =              1215.67
```

- in the hdu=4='DLA' of transmission file, change `DZ_DLA_RSD` to `Z_DLA_RSD`.

- in the hdu=4='DLA' of transmission file, remove `RA, DEC, Z_QSO_NO_RSD, Z_QSO_RSD`.

**Comment by jfarr03** [comment]
I'd certainly agree on the master DLA extname - I'll change that now. I don't really see any harm in repeating the HPX information etc in each HDU, though I can't say I have a particularly strong opinion on the matter. 

In the DLA parts of the transmission files, I've changed the name to Z_DLA_RSD and have removed the other fields you mention already (these changes will appear in the next version).

**Comment by londumas** [comment]
>I don't really see any harm in repeating the HPX information etc in each HDU, though I can't say I have a particularly strong opinion on the matter.

The more I see thing, the more I believe that too much information kills the information. Let's have it only in the hdu=0 or hdu=1.

**Comment by alxogm** [comment]
Hi all, this changes in the fits files are in conflict with the current reading in quickquasars. If you have decided the names and format could you produce a small transmission file to be used for a unitest in quickquasars?  Right now is broken...I can fix it but probably is better if we define the final format.

**Comment by londumas** [comment]
@alxogm, could you point to the line in quickquasar that is making a bug?

**Comment by alxogm** [comment]
@Helion Yes it is: 

File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/mas
ter/py/desisim/scripts/quickquasars.py", line 345, in simulate_one_healpix              
    if (dla['Z_DLA']< metadata[ii]['Z']):
ValueError: no field of name Z_DLA

**Comment by londumas** [comment]
@alxogm, I think @jfarr03 will agree. Let's wait for the next version of London mocks to set the names of the different fields, and then we will update `quickquasars`. Does that sound like a good plan?

**Comment by alxogm** [comment]
> @alxogm, I think @jfarr03 will agree. Let's wait for the next version of London mocks to set the names of the different fields, and then we will update `quickquasars`. Does that sound like a good plan?

OK,I think is fine, when that happens please produce a small transmission file to replace that one in the quickquasar unit test. Thanks.  

Ps. I'll rise an issue in quickquasars so that we don't forget there.

**Comment by londumas** [comment]
@jfarr03, thanks for the work on `v5.0.0`.
the name of `Z_DLA_RSD` is fixed and the duplication of `RA`, `DEC`, `Z_QSO_NO_RSD`, `Z_QSO_RSD` in DLA header is fixed also.
The `EXTNAME` of `master_DLA.fits` is perfect also.
Fixed.
