### ISSUE TITLE
Update format for DLA_ID

### ISSUE THREAD

**Issue by andreufont** [igmhub/LyaCoLoRe#39]
In an email thread with Alma and Xavier we discussed the possibility of using DLA_ID to distinguish only between the different DLAs in a single quasar. DLA_ID then would go from 0 to N-1, where N is the number of DLAs in a given quasar.

In order to identify a DLA, then, you'd need to specify both its DLA_ID and the TARGET_ID of the parent quasar. But any alternative we thought of could be problematic.

**Comment by jfarr03** [comment]
That seems sensible - at the moment the DLA ID is stored as "TARGET_ID"+"DLA number", where "DLA number labels each DLA in the skewer. Thus the current DLA ID specifies both the quasar and the DLA. It would be easy to change this to what you suggest if that's preferable, though!

**Comment by andreufont** [comment]
Actually, I believe the current code does

DLA_ID = TARGET_ID * 1000 + DLA_NUMBER

What it might be good enough, since I don't think we'll ever have more than 1000 systems in a line of sight.

I was now looking at the email thread, and it is possible that this DLA_ID doesn't make it into the DLA catalog, and that is why the confusion started?

**Comment by andreufont** [comment]
mmm... this might be problematic. The largest integer that can be stored in python is 2**32-1 = 4294967295. 

This would imply that the largest TARGET_ID we could handle is int((2**32-1) / 1000) = 4294967. That is not a very large number...

How are we currently setting TARGET_ID? Because I seem to remember that we construct these using also the node used in CoLoRe?

**Comment by jfarr03** [comment]
Yes sorry that was what I meant! I thought that python 3.x no longer has a maximum integer value, though I might have misinterpreted that?

The DLA ID appears in the master_DLA and transmission files now, though this has only been produced for v4.2.0 and later. 

The TARGET_ID is the CoLoRe node number, then 7 digits representing the row-number of the skewer in the original CoLoRe output file.

**Comment by andreufont** [comment]
So i8 means int64? If so, then we should be fine, since it can store up to 10^18... 

If you think you have these things under control we could close this ticket, and document well what DLAID means.

**Comment by andreufont** [comment]
By the way, I noticed that you use some keywords in FITS files that are more than 8 characters long, and I believe these could lead to problems. See, for instance, Z_DLA_NO_RSD.

**Comment by londumas** [comment]
@andreufont, for the more-than-8-character names, it is tracked there: https://github.com/igmhub/LyaCoLoRe/issues/34

**Comment by londumas** [comment]
@andreufont and @alxogm, are the current `DLAID` good for you in `/global/projecta/projectdirs/desi/mocks/lya_forest/london/v5.0.0/master_DLA.fits`?
It is unique to each DLA. If so we can resolve this ticket.
