### ISSUE TITLE
Footprint of random mock DLA

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#45]
The footprint of mock DLAs and random mock DLAs is different.
Would it be possible to have the same footprint?

![footprint_DLA_random](https://user-images.githubusercontent.com/3166436/54440762-f48d8c00-4700-11e9-8835-e57f3ef9f222.png)

**Comment by jfarr03** [comment]
Sure, this shouldn't be hard. Does the footprint need to be precisely the same? 

I ask as the QSO footprints aren't quite identical: the randoms use a strict DESI footprint whereas this version of the mocks extend a bit beyond this. If they need to be precisely the same then it may take a little longer but it is still doable of course.

**Comment by londumas** [comment]
I think the easiest for me is that the footprint is the same in master.fits vs master_randoms.fits and in master_DLA.fits vs master_DLA_randoms.fits. Also you should keep track somewhere, even in an ascii of what seed you used, in order to use different ones for other realizations.
Is all that ok for you?

**Comment by jfarr03** [comment]
Ok I'll set up to make them the same then. 

The seed is recorded in a couple of places, both when I run CoLoRe and then LyaCoLoRe

**Comment by londumas** [comment]
@jfarr03, also when you produce the randoms?

**Comment by jfarr03** [comment]
Oh I see - I'm not sure that is recorded. I'll include that in the modifications

**Comment by londumas** [comment]
@jfarr03, Thanks.

**Comment by londumas** [comment]
fixed in `/global/projecta/projectdirs/desi/mocks/lya_forest/develop/london/v7.3/v7.3.0/master_DLA_randoms.fits`: 
![footprint](https://user-images.githubusercontent.com/3166436/58805141-b3ef3180-85d0-11e9-8f8c-ed75ec831b02.png)
