### ISSUE TITLE
Speed of light should be from scipy.constants

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#58]
The speed of light should be `299792458.0` everywhere, there are no reason to make an approximation. Also it can produce such shift of the correlation function, see issue https://github.com/igmhub/LyaCoLoRe/issues/41.
The best way is to use `from scipy.constants import speed_of_light`, in order not to hard code it nor to cast it to smaller precision.
Doing simple grep, I get:
```
<HOME>/Programs/igmhub/LyaCoLoRe> grep '2.99' -ri * --include \*.py
py/lya_mock_functions.py:        c_kms = 2.998e5
```
This ticket is linked to this more general one: https://github.com/desihub/desisim/issues/477

**Comment by londumas** [comment]
It seems to explain part of the shift of https://github.com/igmhub/LyaCoLoRe/issues/41 `dv = 7.54 km/s`.
```
c = 2.998e5
from scipy.constants import speed_of_light
speed_of_light /= 1000.
dv = c-speed_of_light
print(dv)
```

**Comment by londumas** [comment]
@jfarr03, There might be other places where the speed of light is defined that I have not found.

**Comment by jfarr03** [comment]
@londumas the speed of light isn't used anywhere explicitly in LyaCoLoRe's scripts to produce the mocks - the instance you found isn't used anywhere other than very old examples. I'll correct it nonetheless but it won't be affecting the realisations.

It is almost certainly used in CoLoRe somewhere, though, so I'll have to check exactly what is used there.

**Comment by londumas** [comment]
Ok. Could you send the link to the CoLoRe code ?

**Comment by londumas** [comment]
@jfarr03, is that the one: https://github.com/damonge/CoLoRe?

**Comment by londumas** [comment]
Doing some `grep`s the only thing I found that looks like the spped of light is the following, that seems ok, but has strange units.
https://github.com/damonge/CoLoRe/blob/43abfec9230bd6f37ec3498d499cc61195cb1e5d/src/cosmo_mad.h#L35

**Comment by jfarr03** [comment]
Yes sorry that's the right link - it seems like it's ok but you're right, the units are odd!

**Comment by londumas** [comment]
I just open a ticket there: https://github.com/damonge/CoLoRe/issues/38 to better understand what it is.

**Comment by londumas** [comment]
@jfarr03, could you fix the following line, and then we can close:
`igmhub/LyaCoLoRe/py/lya_mock_functions.py:        c_kms = 2.998e5`
I know it is not used, but let's fix that so it does not show up.
Thanks for the help.

**Comment by jfarr03** [comment]
@londumas fixed in commit https://github.com/igmhub/LyaCoLoRe/commit/4ed3ebff13de5f2aed4ff9318ae4fa7b6000839a

**Comment by londumas** [comment]
@jfarr03, thanks
