### ISSUE TITLE
Save Pk in code or/and in repository production

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#62]
Save P(k) in code or/and in repository production. Where is it saved for the moment?

**Comment by londumas** [comment]
We also need to save the intup parameters of CAMB and the parameters (Omega_m) used in the box to transform z to r

**Comment by jfarr03** [comment]
@londumas by P(k) I assume you mean the input power spectrum to CoLoRe? At the moment the input power spectrum and cosmological parameters (as well as N(z), b(z) of QSOs) are not stored in LyaCoLoRe, but I've been intending to add them for a while. It shouldn't take much effort but other things have been prioritised recently! I'll try to do it today so this can be ticked off.

**Comment by londumas** [comment]
Yes ghe input P(k) so that I can be exactly sure of what you guys use. The
best would be to also sqve the .ini of CAMB and an ascii with redshift and
distance from 0 to 4. To see if we agree on the computation of distances

**Comment by jfarr03** [comment]
Ok sure - I don't know where the CAMB .ini file is stored but I'll try to find out. The redshift-distance relation is stored in the master.fits file at the moment: the extension "COSMO_COL" contains the data from CoLoRe and the extension "COSMO_EXP" contains the "expanded" data (i.e. smaller cells) in LyaCoLoRe

**Comment by londumas** [comment]
ok, at least the P(k) is good. but the .ini is even better because anybody in 10 years will be able to reproduce exactly the output. Can you send me via email the P(k) or tell me where to find it?

**Comment by londumas** [comment]
@jfarr03, Storing the redshift-distance relation in the master is a very good idea.
It would be good if you could add Some comments and the dimension to each variable in `COSMO_COL` and `COSMO_EXP`.
Looking at this I think it would make a lot of sense to store the P(k) in master.fits also, in an other HDU, with the cosmological parameters in the header.
What do you think?

**Comment by londumas** [comment]
@jfarr03, why do you need a different `COSMO_COL` and `COSMO_EXP`. Is the cosmology different in big and small cells?

**Comment by londumas** [comment]
@jfarr03, here are the results of BAO measurement on the simulations.
Where the first column is alpha_parallel, the second alpha_perp.
For the two columns, I give the mean, then std/sqrt(10), then the mean error and then the mean error / sqrt(10).
There is a small, compatible with statistics, shift of alpha_parallel.
That is one of the reason I would need the power spectrum, so I can see if it is real or likely statistical.

```
 || cf Ly\alpha                   ||  1.0206 +/- 0.0039 (0.0256,0.0081) ||  0.9885 +/- 0.0076 (0.0294,0.0093) ||  16132.26 / (15900-60)|| 
 || cf Ly\alpha+Continuum         ||  1.0195 +/- 0.0096 (0.0360,0.0114) ||  1.014 +/- 0.033 (0.055,0.017) ||  15904.32 / (15900-60)|| 
 || cf Ly\alpha+Continuum+HCDs    ||  1.0176 +/- 0.0097 (0.0385,0.0122) ||  1.001 +/- 0.032 (0.065,0.021) ||  16129.94 / (15900-60)|| 

 || xcf Ly\alpha                  ||  1.0071 +/- 0.0089 (0.0288,0.0091) ||  0.9893 +/- 0.0079 (0.0260,0.0082) ||  32290.84 / (31800-80)||
 || xcf Ly\alpha+Continuum        ||  1.034 +/- 0.012 (0.043,0.014)     ||  0.977 +/- 0.012 (0.037,0.012) ||  31860.10 / (31800-80)|| 
 || xcf Ly\alpha+Continuum+HCDs   ||  1.039 +/- 0.013 (0.042,0.013)     ||  0.967 +/- 0.014 (0.040,0.013) ||  31928.77 / (31800-80)|| 

 || cfxcf Ly\alpha+Continuum      ||  1.0274 +/- 0.0052 (0.0288,0.0091) ||  0.9849 +/- 0.0094 (0.0298,0.0094) ||  48498.73 / (47700-90)|| 
 || cfxcf Ly\alpha+Continuum+HCDs ||  1.0264 +/- 0.0056 (0.0295,0.0093) ||  0.978 +/- 0.012 (0.034,0.011) ||  48764.89 / (47700-90)|| 
```

**Comment by londumas** [comment]
Here is the comparison between the distances computing using picca and from the master.fits:
![distances](https://user-images.githubusercontent.com/3166436/56241900-46a13480-6054-11e9-83f6-02f0a8d41a3f.png)

**Comment by andreufont** [comment]
Hi @londumas - what version of the mocks are you using? is this on the eBOSS footprint, I assume, or in the full sky?

**Comment by londumas** [comment]
I used the last 10:  v6.0

**Comment by jfarr03** [comment]
The input data to CoLoRe is now stored in the directory "run_CoLoRe". The input bias and number density of QSOs, as well as the input power spectrum is in the sub-directory "input_files", and the cosmological parameters are readable from the script run_CoLoRe.sh. 

I don't have a .ini file from CAMB I'm afraid, but I believe that I got the input power spectrum from picca a while ago (it doesn't seem to be there any more) and that it came from the file https://github.com/igmhub/picca/blob/master/py/picca/fitter2/models/PlanckDR12/PlanckDR12_kmax_params.ini.

**Comment by londumas** [comment]
@jfarr03, thank you for that.
I will have a look.

**Comment by londumas** [comment]
@jfarr03, it is perfect. The difference between your P(k) and the one output by CAMB, using picca .ini file is very small. Everything looks good.
![difference_of_pk](https://user-images.githubusercontent.com/3166436/57031987-69ac1680-6c06-11e9-84b4-c1a503aa8ff0.png)
