### ISSUE TITLE
TRANSMISSION no longer in transmission-16-*.fits files

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#82]
@jfarr03, I see that `TRANSMISSION` no longer is in `/global/projecta/projectdirs/desi/mocks/lya_forest/develop/london/v7.3/v7.3.0/0/0/transmission-16-0.fits` files. Is that permanent, or is that for a test?
```
desi_header /global/projecta/projectdirs/desi/mocks/lya_forest/develop/london/v7.3/v7.3.0/0/0/transmission-16-0.fits --info

no key, will dump header
/global/projecta/projectdirs/desi/mocks/lya_forest/develop/london/v7.3/v7.3.0/0/0/transmission-16-0.fits
======================
Filename: /global/projecta/projectdirs/desi/mocks/lya_forest/develop/london/v7.3/v7.3.0/0/0/transmission-16-0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1  METADATA      1 BinTableHDU     23   2577R x 5C   [E, E, E, E, K]   
  2  WAVELENGTH    1 ImageHDU        11   (15150,)   float32   
  3  F_LYA         1 ImageHDU        12   (15150, 2577)   float32   
  4  F_LYB         1 ImageHDU        13   (15150, 2577)   float32   
  5  F_SI1260      1 ImageHDU        13   (15150, 2577)   float32   
  6  F_SI1207      1 ImageHDU        13   (15150, 2577)   float32   
  7  F_SI1193      1 ImageHDU        13   (15150, 2577)   float32   
  8  F_SI1190      1 ImageHDU        13   (15150, 2577)   float32   
  9  DLA           1 BinTableHDU     23   1774R x 5C   [E, E, E, K, K]   

<bound method Header.tostring of SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                    8 / array data type                                
NAXIS   =                    0 / number of array dimensions                     
EXTEND  =                    T                                                  >

```

**Comment by jfarr03** [comment]
@londumas Yes this was discussed at a couple of recent telecons I think - for the purposes of tuning the strengths of metal absorbers, it's easier to have each metal's absorption stored in a separate HDU. The idea is that then one realisation can be made and you can choose which metals to add when running quickquasars with an option that looks something like:

`--add-absorbers SI1260 SI1207`

Obviously this requires a bit of modification to quickquasars but hopefully not too much? I think @Andrea-MG is looking into this?

**Comment by andreufont** [comment]
There are two different things:
 - changes in how to add metals from file, using an individual HDU for each metal.
 - changes in how to add LyA and LyB, using an individual HDU for each, instead of the old TRANSMISSION HDU that had both together.

This allows us to use the same transmission file to generate mocks with only LyA, and mocks with LyA and LyB. 

For now, I would just add a quick try / catch in quickquasars that looks for F_LYA if the HDU TRANSMISSION does not exist.

**Comment by londumas** [comment]
changed for "F_LYA" and works.
