### ISSUE TITLE
n(z) mock random HCD distribution low z tail 

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#84]
The low z tail, and the overall z distribution of HCDs is different between mock HCD and random mock HCD.
With @TEtourneau, we have seen that it could be linked to the clustering of mock HCD compared to the lack of clustering of random mock HCD. One way to fix that is to down-sample the mock random distribution to the mock distribution. 

![all_nz](https://user-images.githubusercontent.com/3166436/58810183-a8a10380-85da-11e9-968f-45feca35c851.png)

![nz_low_tail](https://user-images.githubusercontent.com/3166436/58810180-a8a10380-85da-11e9-9e6f-8edd42e21e5a.png)

![nz_high_tail](https://user-images.githubusercontent.com/3166436/58810181-a8a10380-85da-11e9-9059-302b3f15c197.png)

**Comment by jfarr03** [comment]
@londumas I think this looks good at the high-z end? At the low-z end the issue is mostly because the master_DLA file contains DLAs at wavelength lower than the minimum wavelength of the skewers as a result of the order in which various operations are carried out by LyaCoLoRe.

It's fixed in the code now, so future versions of the mocks won't have this issue. In the meantime, I've generated randoms which extend to a lower wavelength to match v7.3. The match is certainly much closer but it is still not perfect at the moment - let me know if it's good enough or if more precision is required!

**Comment by jfarr03** [comment]
Actually, I'm generating a new version now which I think will be more precise, so let's wait for that to finish!

**Comment by londumas** [comment]
@jfarr03, looks good now, even if not perfect. Am-I using the latest file? If yes, it is good enough to me.

![all](https://user-images.githubusercontent.com/3166436/58878644-f7a97000-8690-11e9-8124-fe9f5ac9ad06.png)

![low_z](https://user-images.githubusercontent.com/3166436/58878645-f7a97000-8690-11e9-9384-0151a8e99f03.png)

![high_z](https://user-images.githubusercontent.com/3166436/58878647-f8420680-8690-11e9-9653-e8f7f875825b.png)

**Comment by jfarr03** [comment]
Yes this looks like the latest version. As I say - there's a new version running now, which I think will be better still. I'll check that once it's finished running and will update on here

**Comment by TEtourneau** [comment]
@jfarr03 Do you still use the numpy.random.choice function to produce the random DLA ?
Is the redshift of the random DLA lower than the host QSO ?

**Comment by londumas** [comment]
@TEtourneau, to the last question I can answer. In the lasts plots of ticket https://github.com/igmhub/LyaCoLoRe/issues/40, you can see that indeed mock DLA and random mock DLA have z<z_QSO, which is very good.

**Comment by jfarr03** [comment]
@TEtourneau yes as @londumas said, the DLAs all have z_DLA<z_QSO. 

I don't use numpy.random.choice for getting z_DLA_rnd any more, however it is used to assign each DLA to a QSO. The two options to get the z_DLA_rnd are:

 - "from_catalog": measure dn/dz from the real DLA catalog, draw z_DLA_rnd from that distribution, place the DLAs in QSOs with z_DLA<z_QSO at random
 - "cdf": use pyigm to get dndz, draw z_DLA_rnd from that distribution, place the DLAs in QSOs at random, ignore DLAs with z_DLA>z_QSO, add a gaussian "RSD" effect using sigma_RSD measured from the catalog

Hopefully that makes sense - the code in https://github.com/igmhub/LyaCoLoRe/blob/master/desi/generate_rnd_dla.py is now fully commented so should be clear too now. Let me know if you've got any questions!

**Comment by TEtourneau** [comment]
I'm having a look to the code, thanks.
Is that code long to run ?

**Comment by jfarr03** [comment]
It depends on the value you choose for "factor" - if you go for factor=10, then it does take a while but that's generating ~25*10^6 DLAs. If you go for factor=0.1 instead, then it runs in less than a minute.

**Comment by londumas** [comment]
fixed, thanks @jfarr03
