### ISSUE TITLE
same MOCKID in mock QSO and random mock QSO

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#85]
Between mock QSO and random mock QSO, some have the same MOCKID.
This should not be the case since it leads to rejecting these pairs `RD` when computing the auto-correlation of quasars. @jfarr03 could you fix that? How do you assign MOCKID? randomly or according to the cell the quasar is in? I bet the first option since two objects with the same MOCKID do not have the same RA, DEC.

```
paths = '/global/projecta/projectdirs/desi/mocks/lya_forest/develop/london/v7.3/v7.3.0/'
cat = {
    'QSO':{'PATH':paths+'/master.fits'},
    'randQSO':{'PATH':paths+'/master_randoms.fits'}
    }

for o in cat.keys():
    h = fitsio.FITS(cat[o]['PATH'])
    for k in ['RA','DEC','MOCKID']:
        cat[o][k] = h['CATALOG'][k][:]
    h.close()
    
    w = sp.argsort(cat[o]['MOCKID'])
    for k in ['RA','DEC','MOCKID']:
        cat[o][k] = cat[o][k][w]

###
for o in cat.keys():
    print(o, cat[o]['MOCKID'].size, sp.unique(cat[o]['MOCKID']).size)

###
w1 = sp.in1d(cat['QSO']['MOCKID'],cat['randQSO']['MOCKID'])
print('QSO in randQSO: {}'.format(w1.sum()))
print(cat['QSO']['MOCKID'][w1])

###
w2 = sp.in1d(cat['randQSO']['MOCKID'],cat['QSO']['MOCKID'])
print('randQSO in QSO: {}'.format(w2.sum()))
print(cat['randQSO']['MOCKID'][w2])

###
w = cat['QSO']['MOCKID'] == cat['QSO']['MOCKID'][w1][0]
for k in ['RA','DEC','MOCKID']:
        print('QSO', cat['QSO'][k][w])
###
w = cat['randQSO']['MOCKID'] == cat['QSO']['MOCKID'][w1][0]
for k in ['RA','DEC','MOCKID']:
        print('randQSO', cat['randQSO'][k][w])
```

it gives the following:
```
QSO 3618455 3618455
randQSO 5993302 5993302
QSO in randQSO: 85077
[       1        5        7 ... 10261313 10261315 10261316]
randQSO in QSO: 85077
[       1        5        7 ... 10261313 10261315 10261316]
QSO [44.80036545]
QSO [18.89311981]
QSO [1]
randQSO [112.4692432]
randQSO [73.72283554]
randQSO [1]
```

**Comment by jfarr03** [comment]
@londumas this should be fixed in the latest version: the randoms have MOCKID starting at 10^10, whereas the QSOs from the mocks are always less than 3.2*10^9

**Comment by andreufont** [comment]
Hi @jfarr03 - this looks good, but just in case I would add a check that the number of QSO is always less than 1e10, and make the code crash if this is not the case.

**Comment by jfarr03** [comment]
Sure - I don't think it will be an issue for anything we'll be doing, but I'll add a warning flag to the randoms script if this is not the case for whatever reason.

**Comment by andreufont** [comment]
yes, I think this is only relevant for future runs (someone might want to generate mocks that extend to very low-z, to add CIV or whatever. In these type of cases, it is always better to raise VauleError than to print a warning.

**Comment by jfarr03** [comment]
It is always possible to raise a warning and then just increase the starting value of the randoms' MOCKID? Or just raise an error as you suggest

**Comment by andreufont** [comment]
What is the maximum value for MOCKID that the code would be able to handle? I'd first check what is the largest integer than python and FITS files can handle. You want to find a setting that can satisfy two conditions:
 - no qsos with the same value of MOCKID (either mock or random qso)
 - no quso with MOCKID larger than the maximum that can be handled by python or FITS.

You can code this up in many different ways, the only thing important is that the code doesn't silently breaks the conditions above.

**Comment by jfarr03** [comment]
I don't think there's a maximum value integer in python 3, though I'm not sure about FITS files so I'll check that. 

This is also relevant to the DLAID assigned to random DLAs I guess - it is more likely to be an issue there as the DLAs in the mocks are given DLAID = MOCKID*100 + (DLA_IN_SKW_ID) where DLA_IN_SKW_ID is an integer that labels the DLAs in each skewer from 0 upwards. 

At the moment random DLAs are just given a DLAID with a number greater than 100*max(MOCKID) to avoid any conflict with non-random DLAs, so this results in numbers around 10^12.

**Comment by jfarr03** [comment]
It seems FITS can handle 64-bit integers, so the maximum is ~10^18.96, so these numbers should be well within that. I'll add in an error if any of the ID numbers exceed this

**Comment by londumas** [comment]
Fixed. Thanks @jfarr03 and @andreufont .
