### ISSUE TITLE
random quasar is different than real

### ISSUE THREAD

**Issue by londumas** [igmhub/LyaCoLoRe#94]
Comparing the mock random quasar catalog and the mock data quasar catalog, we can see that something is happening at the DEC==0. @jfarr03, do you have any idea of what is happening? An overflow of some sort? This is using v9.0.0, but I observe that also on v9.0.1. If this is real you should also have the issue on the plot of your paper. Could you have a look? I am trying to compute the auto-correlation of quasars to look at its correlation with the autoLya and crossLyaQSO.
![rand_vs_data](https://user-images.githubusercontent.com/3166436/66408276-f72e3680-e9ee-11e9-9d4f-343c8180e106.png)

**Comment by jfarr03** [comment]
I've found the bug - it was a simple error fortunately. I'll generate a new set of randoms now and will let you know when it's done so you can check, @londumas.

**Comment by londumas** [comment]
@jfarr03, sounds perfect. I am confused that it did not show up on the plot for your paper.

**Comment by jfarr03** [comment]
The bug is only related to imposing the desi footprint, whereas the realisations I used for the paper are full sky so were unaffected

**Comment by londumas** [comment]
@jfarr03, I see. Thanks for the help.

**Comment by jfarr03** [comment]
@londumas the file for v9.0.0 has finished and the histogram looks more sensible - can you check that the footprint plot looks ok now?

**Comment by londumas** [comment]
Hi @jfarr03, looks good. Let me run the auto-correlation of quasar and I will confirm that to you.
![random_data](https://user-images.githubusercontent.com/3166436/66413370-87707980-e9f7-11e9-8a6f-c4779e8d8612.png)

**Comment by jfarr03** [comment]
Great, thanks - once you've confirmed I'll re-run all of the other realisations as well

**Comment by londumas** [comment]
@jfarr03, works perfectly. Can you reproduce the random catalogs for all the realizations?

**Comment by jfarr03** [comment]
Great! Yes will do - it'll take a while to run but I'll let you know once it's finished

**Comment by londumas** [comment]
perfect.

**Comment by jfarr03** [comment]
@londumas All realisations have now finished running - I've checked the histograms for the a random 10 realisations and they all look good

**Comment by londumas** [comment]
@jfarr03, perfect. Thanks for fixing that.

**Comment by jfarr03** [comment]
No problem!
